sudo: required
services: 
  - docker

before_install:
  - docker build -t manojdec22/react-docker -f Dockerfile.dev .  

script:
  - docker run -e CI=true manojdec22/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-423908626173"
  bucket_path: "react-docker"
  on:
    branch: "master"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  